# Generated by Django 5.2.7 on 2025-11-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.URLField(blank=True, help_text='URL to book cover image', max_length=500, null=True),
        ),
    ]
